models/Projects.py
from config import Config 
from database import db
from lib.generate_timestamp import generate_timestamp
from lib.generate_uuid import generate_uuid

class Projects(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    uid = db.Column(db.String(200), nullable=False, default=generate_uuid())
    timestamp = db.Column(db.DateTime, nullable=False, default=generate_timestamp())

    url = db.Column(db.String(256))
    title = db.Column(db.String(Config.LEN['title']), nullable=False, default="")
    codename = db.Column(db.String(Config.LEN['title']), nullable=False, default="")
    project_type = db.Column(db.String(200), nullable=False, default="")
    project_category = db.Column(db.String(200), nullable=False, default="")
    project_image = db.Column(db.String(Config.LEN['url']))
    project_url = db.Column(db.String(Config.LEN['url']))
    description = db.Column(db.String(Config.LEN['content']), nullable=False, default="")
    featured = db.Column(db.Boolean, nullable=False, default=False)

    def __repr__(self):
        return self.title

routes/blog.py
from flask import Blueprint, request, render_template 
from lib.return_blogs import return_blogs 
from lib.return_projects import return_projects
from lib.gen_sc import gen_sc 
from config import Config

blog_blueprint = Blueprint("blog", __name__)

# Blog Posts
@blog_blueprint.route("/blog/")
def blog() -> str:
    blogs = return_blogs()
    projects = return_projects()
    return render_template("blog.html", blogs=blogs, projects=projects, ts=Config.STRFTIME_FORMAT, sc=gen_sc(request))

routes/home.py
from flask import Blueprint, request, render_template
from sqlalchemy.sql import desc 
from config import Config
from lib.gen_sc import gen_sc
from lib.return_blogs import return_blogs
from lib.return_projects import return_projects

home_blueprint = Blueprint("home", __name__)

@home_blueprint.route("/")
def home():
    projects = return_projects()
    blogs = return_blogs()

    return render_template("home.html", blogs=blogs, projects=projects, strf=Config.STRFTIME_FORMAT, sc=gen_sc(request))

routes/in_blog.py
from flask import Blueprint, render_template, request, abort
from lib.gen_sc import gen_sc
from lib.return_projects import return_projects
from models.BlogPosts import BlogPosts
from markdown2 import markdown
from config import Config

in_blog_blueprint = Blueprint("in_blog", __name__)

# Inside blog
@in_blog_blueprint.route("/blog/<string:blog>/")
def in_blog(blog):
    blog_post = BlogPosts.query.filter_by(uid=blog).first()
    projects = return_projects()

    if blog_post != [None, ""]:
        markdown_as_html = markdown(blog_post.content)
        blog_post_formatted = {
            "uid": blog_post.uid,
            "timestamp": blog_post.timestamp,
            "title": blog_post.title,
            "content": markdown_as_html 
        }

        return render_template("in_blog.html", blog=blog_post_formatted, projects=projects, ts=Config.STRFTIME_FORMAT, sc=gen_sc(request))
    else:
        abort(404)

routes/project_route.py
from flask import Blueprint, render_template, request
from lib.gen_sc import gen_sc
from lib.return_projects import return_projects

projects_route_blueprint = Blueprint("projects_route", __name__)

@projects_route_blueprint.route("/projects/")
def projects_route() -> str:
    projects = return_projects()
    return render_template("projects.html", projects=projects, sc=gen_sc(request))

routes/signin.py
from flask import Blueprint, request, render_template, url_for, redirect, make_response
from config import Config
from lib.gen_sc import gen_sc
from lib.verify_admin import verify_admin
from datetime import datetime, timedelta

signin_blueprint = Blueprint("signin", __name__)

@signin_blueprint.route("/signin/", methods=["GET", "POST"])
def signin():
    if request.method == "POST": 
        if verify_admin() == False:
            token = request.form.get("token", None)

            if token != None: 
                if str(token) == Config.SECRET_ACCESS_COOKIE: 
                    resp = make_response(redirect(url_for("home.home")))
                    expire_date = datetime.now()
                    expire_date = expire_date + timedelta(days=90)

                    resp.set_cookie("token",
                        value=str(token), 
                        expires=expire_date
                    )

                    return resp


            return redirect(url_for("signin.signin"))
        else: 
            return redirect(url_for("home.home"))

    if verify_admin() == False:
        return render_template("signin.html", strf=Config.STRFTIME_FORMAT, sc=gen_sc(request))
    else:
        return redirect(url_for("home.home"))

templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.3/semantic.min.css" integrity="sha512-3quBdRGJyLy79hzhDDcBzANW+mVqPctrGCfIPosHQtMKb3rKsCxfyslzwlz2wj1dT8A7UX+sEvDjaUv+WExQrA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="/static/css/fomantic.css">
</head>
<body>
    <div class="ui container wrapper" style="margin-top: 25px;">
        <header>
            <h1 class="ui dividing header">
                Admin Panel
            </h1>

            <a href="/" rel="noopener noreferrer">Back to Website</a>
            <a class="logout-button" rel="noopener noreferrer">Log out</a>
        </header>

        <main>
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <section class="flashed-messages">
                        {% for m in messages %}
                            <div class="ui green message">
                                <p>{{ m }}</p>
                            </div>
                        {% endfor %}
                    </section>
                {% endif %}
            {% endwith %}

            <section>
                <h2 class="ui header">Add Project</h2>
                <form action="/admin" method="post" class="ui form" enctype="multipart/form-data">
                    <div class="ui field">
                        <div class="ui labeled input">
                            <div class="ui label">Title</div>
                            <input type="text" class="project-title" name="project-title" id="project-title" placeholder="Project Title" required>
                        </div>
                    </div>

                    <div class="ui field">
                        <div class="ui labeled input">
                            <div class="ui label">Codename (optional)</div>
                            <input type="text" class="project-codename" name="project-codename" id="project-codename" placeholder="Project Codename (optional)">
                        </div>
                    </div>

                    <div class="ui field">
                        <div class="ui labeled input">
                            <div class="ui label">URL (optional)</div>
                            <input type="text" class="project-url" name="project-url" id="project-url" placeholder="Project URL (optional)">
                        </div>
                    </div>

                    <div class="ui field">
                        <div class="ui labeled input">
                            <div class="ui label">Type</div>

                            <select class="ui selection dropdown" name="project-type">
                                <option value="empty">Select One *</option>
                                <option value="books">Books</option>
                                <option value="games">Games</option>
                                <option value="manga">Manga</option>
                                <option value="software">Software: General programs for desktop or mobile.</option>
                                <option value="web">Web: Web applications. They can have software associated with them, but are not primarly software-based.</option>
                            </select>
                        </div>
                    </div>

                    <div class="ui field">
                        <div class="ui labeled input">
                            <div class="ui label">Category</div>

                            <select class="ui selection dropdown" name="project-category">
                                <option value="empty">Select One *</option>
                                <option value="completed">Completed: Is done and available to the public, many times recieving updated</option>
                                <option value="construction">Under Construction: Currently being worked on</option>
                                <option value="scrapped">Scrapped: Not done and never will be</option>
                            </select>
                        </div>
                    </div>

                    <div class="ui field">
                        <label for="project-desc">Project Desc</label>
                        <div class="ui corner labeled input">
                            <textarea name="project-desc" id="project-desc" cols="30" rows="10" placeholder="Project Desc" required></textarea>

                            <div class="ui corner label">
                                <i class="asterisk icon"></i>
                            </div>
                        </div>
                    </div>

                    <div class="ui field">
                        <label for="project-featured">Feature the project?</label>

                        <span>Yes: </span><input type="radio" name="project-featured" value="yes" id="project-featured">
                        <span>No: </span><input type="radio" name="project-featured" value="no" id="project-featured">
                    </div>

                    <div class="ui field">
                        <label for="image">Image: </label>
                        <input type="file" class="button" name="project-image" id="image">
                    </div>

                    <input class="ui button" type="submit" value="Submit Project">
                </form>

            </section>

            <div class="ui divider"></div>

            <section>
                <h2 class="ui header">Add Blog</h2>

                <form action="/admin" class="ui form" method="POST">
                    <div class="ui field">
                        <div class="ui labeled input">
                            <div class="ui label">Title</div>
                            <input type="text" class="blog-title" name="blog-title" id="blog-title" placeholder="Blog Title" required>
                        </div>
                    </div>

                    <div class="ui field">
                        <div class="ui labeled input">
                            <div class="ui label">Summary</div>
                            <input type="text" class="blog-summary" name="blog-summary" id="blog-summary" placeholder="Blog Summary" required>
                        </div>
                    </div>

                    <div class="ui field">
                        <textarea name="blog-content" id="" cols="30" rows="10" placeholder="Content" required></textarea>
                    </div>

                    <input type="submit" value="Submit Blog Post" class="ui button">
                </form>
            </section>
        </main>
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.3/semantic.min.js" integrity="sha512-gnoBksrDbaMnlE0rhhkcx3iwzvgBGz6mOEj4/Y5ZY09n55dYddx6+WYc72A55qEesV8VX2iMomteIwobeGK1BQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/js-cookie/3.0.5/js.cookie.min.js" integrity="sha512-nlp9/l96/EpjYBx7EP7pGASVXNe80hGhYAUrjeXnu/fyF5Py0/RXav4BBNs7n5Hx1WFhOEOWSAVjGeC3oKxDVQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        function logout() {
            console.log("THIS RAN")
            const logout_button = document.querySelector(".logout-button")

            if (logout_button != null && logout_button != undefined) {
                logout_button.addEventListener("click", () => {
                    Cookies.remove("token")
                    location.href = "/"
                })
            }
        }

        logout()
    </script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | sinistra-website</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/bundle.css') }}">

    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Favicons -->
    <link rel="apple-touch-icon" sizes="180x180" href="/static/images/favicons/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/static/images/favicons/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/static/images/favicons/favicon-16x16.png">
    <link rel="manifest" href="/static/images/favicons/site.webmanifest">
    <link rel="mask-icon" href="/static/images/favicons/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="/static/images/favicons/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="/static/images/favicons/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

    <!-- Meta -->
    <meta name="author" content="Sinistra">
    <meta name="keywords" content="s1nistr4, sinistra, sinistra website, lewdtropolis, super mario retro">
    <meta name="description" content="my personal website">

    <meta name="author" content="s1nistr4" />

    <!-- Prevents the dark theme from destroying your website -->
    <meta name="color-scheme" content="light only">

    <meta property="og:site_title" content="s1nistr4 website" />
    <meta property="og:title" content="s1nistr4 website" />
    <meta property="og:description" content="my personal website" />
    
    <!-- Site Image -->
    <meta property="og:image" itemprop="image" content="{{ url_for('static', filename='images/me3.jpg') }}" />
    <meta property="og:image:width" content="300" />
    <meta property="og:image:height" content="300" />
    <meta property="og:image:type" content="image/png" />
</head>

<body>
    <div class="wrapper">
        <header>
            <div class="left-content">
                <span class="sidebar-enter-button"><i class="fa-solid fa-bars"></i></span>
                <span class="cover-enter-button"><i class="fa-solid fa-bars"></i></span>

                <a href="/" class="link-content-frame">
                    <div class="left-info-content">
                        <img class="me" src="{{ url_for('static', filename='images/me.jpg') }}" alt="me, aka gigachad">
                        <p> S1nistr4 Website</p>
                    </div>
                </a>
            </div>

            <ul class="links">
                <li class="link header-link" data-link="{{ url_for('home.home') }}">
                    <lottie-player autoplay loop mode="normal"
                            src="/static/icons/home.json"
                            style="display: inline-block; width: 38px"
                    ></lottie-player>
                    <span class="link-text">Home</span>
                </li>

                <li class="link header-link" data-link="{{ url_for('projects_route.projects_route') }}">
                    <lottie-player autoplay loop mode="normal"
                            src="/static/icons/projects.json"
                            style="display: inline-block; width: 38px"
                    ></lottie-player>
                    <span class="link-text">Projects</span></span>
                </li>

                <li class="link header-link" data-link="{{ url_for('blog.blog') }}">
                    <lottie-player autoplay loop mode="normal"
                            src="/static/icons/blog.json"
                            style="display: inline-block; width: 38px"
                    ></lottie-player>
                    <span class="link-text">Blog</span>
                </li>

                {% if sc.header == sc.key %}
                    <li class="link header-link" data-link="{{ url_for('admin.admin') }}">
                        <lottie-player autoplay loop mode="normal"
                                src="/static/icons/admin.json"
                                style="display: inline-block; width: 38px"
                        ></lottie-player>
                        <span class="link-text"> Admin</span>
                    </li>
                {% endif %}
            </ul>
        </header>

        <main>
            {% block main %}{% endblock %}
        </main>

        {# Overlay Features #}
        <div class="sidebar-cover"></div>
        <div class="sidebar">
            <div class="sidebar-content">
                <span><i class="fa-solid fa-bars sidebar-exit-button"></i></span>
                <div class="sidebar-section">
                    <h1 class="sidebar-title">Projects</h1>
                    <p class="sidebar-subtitle">These are all of my projects in alphabetical order.</p>
                    {% if projects %}
                        <ul class="sidebar-projects">
                            {% for project in projects %}
                                {% if project.project_url %}
                                    <li class="sidebar-project"><a href="{{ project.project_url }}" rel="noopener noreferrer" target="_blank">{{ project.title }}</a></li>
                                {% else %}
                                    <li class="sidebar-project">{{ project.title }}</li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
            </div>
        </div>

        <div class="cover">
             <div class="sidebar-content">
                <span><i class="fa-solid fa-bars cover-exit-button"></i></span>
                <div class="sidebar-section">
                    <h1 class="sidebar-title">Projects</h1>
                    <p class="sidebar-subtitle">These are all of my projects in alphabetical order.</p>
                    {% if projects %}
                        <ul class="sidebar-projects">
                            {% for project in projects %}
                                {% if project.project_url %}
                                    <li class="sidebar-project"><i class="fa-solid fa-circle-arrow-right"></i> <a href="{{ project.project_url }}" rel="noopener noreferrer" target="_blank"> {{ project.title }}</a></li>
                                {% else %}
                                    <li class="sidebar-project"><i class="fa-solid fa-circle-arrow-right"></i> {{ project.title }}</li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    {% endif %}
                </div>
             </div>
        </div>
    </div>

    <footer>
        <div class="footer-left">
            <p class="footer-copyright">&copy ock</p>
            <a href="https://gitlab.com/s1nistr4/sinistra-website" rel="noopener noreferrer" target="_blank" >Source Code</a>
        </div>
        
        <div class="social-links">
            <a href="https://mastodon.world/@s1nistr4" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-mastodon social-icon"></i></a>
            <a href="https://odysee.com/@s1nistr4:b" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-odysee social-icon"></i></a>
            <a href="https://communities.win/u/s1nistr4" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-stripe-s social-icon"></i></a>

            <a style="text-decoration: none" href="mailto:s1nistr4@proton.me" target="_blank" rel="noopener noreferrer">
                <i class="fa-solid fa-envelope social-icon"></i>
            </a>

            <a style="text-decoration: none" href="https://lemmy.world/u/s1nistr4" target="_blank" rel="noopener noreferrer">
                <img class="social-icon" style="width: 50px; height: 28px" src="{{ url_for('static', filename='images/lemmy.webp') }}" />
            </a>

        </div>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/lottie-player/2.0.2/lottie-player.js" integrity="sha512-NcJNVDzfhHalE0Dj3s8ub4hW0QYw1hfk05I53N3MTXOYDDGt0wpXmAPve+GhmmdDxik8pTUONQjeNKDO/p7rhQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <video class="video-background" src="/static/videos/heart.mp4" autoplay muted loop></video>
    <script src="{{ url_for('static', filename='js/global.js') }}"></script>
</body>
</html>

templates/blog.html
{% extends "base.html" %}
{% block title %}le blog{% endblock %}
{% block main %}
    <div class="section home-welcum-section">
        <span class="welcome-title">
            <span class="letter">B</span>
            <span class="letter">l</span>
            <span class="letter">o</span>
            <span class="letter">g</span>
        </span>
        <p class="welcome-subtitle">Where I write about stupid bullshit.</p>
    </div>

    <section class="section">
        {% if blogs %}
            {% for i in blogs %}
                <div class="content-area wide content-area-blue">
                    <h2 class="content-area-top content-top-blue"><i class="fa-solid fa-globe di"></i> {{ i.title }}</h2>
                    <div class="content-area-bottom">
                        <p class="blog-post-timestamp">{{ i.timestamp.strftime(ts) }}</p>
                        <p class="blog-post-content">{{ i.summary }}</p>
                        <a href="{{ url_for('in_blog.in_blog', blog=i.uid) }}"><button class="button">Read More</button></a>
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </section>
{% endblock %}

templates/bp.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block main %}{% endblock %}

templates/home.html
{% extends "base.html" %}
{% block title %}w3lc0me 2 h3ll{% endblock %}
{% block main %}
    <div class="section home-welcum-section">
        <div class="home-welcum-content">
            <img src="{{ url_for('static', filename='images/me2.webp') }}" class="profile-icon" alt="profile icon">

            <div class="title-area">
                <h1 class="title-area-heading">♥~Welcum~♥</h1>
                <p class="title-area-subtitle">to my website</p>
            </div>
        </div>
    </div>

    <div class="page-content">
        <section class="section">
            <div class="content-area content-area-red">
                <h2 class="content-area-top content-top-red"><i class="fa-solid fa-circle-info di"></i> About</h2>
                <div class="content-area-bottom">
                    <p>CEO <span class="star">☆</span> Crypto Enterpreneur <span class="star">☆</span> Vegan <span class="star">☆</span> Masters in Psychology <span class="star">☆</span> Dating Coach <span class="star">☆</span> 128 IQ <span class="star">☆</span> Free Thinker <span class="star">☆</span> Kali Linux User <span class="star">☆</span> Sigma Male <span class="star">☆</span> PHP Developer <span class="star">☆</span> League <span class="star">☆</span> ACAB <span class="star">☆</span> Furry <span class="star">☆</span> Discord Moderator <span class="star">☆</span>  Nofap</p>
                </div>
            </div>
        </section>

        <section class="section">
            <div class="content-area content-area-blue">
                <h2 class="content-area-top content-top-blue"><i class="fa-solid fa-list-check di"></i> Featured Projects</h2>
                <div class="content-area-bottom">
                    <p>projects imma working on</p>

                    <div class="projects">
                        {% if projects %}
                            {% for project in projects[:3] %}
                                {% if project.featured == True %}
                                    {% include("includes/project_box.html") %}
                                {% endif %}
                            {% endfor %}
                        {% else %}
                            <div class="no-content">
                                <p>No projects?</p>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </section>

        <section class="section">
            <div class="content-area content-area-green">
                <h2 class="content-area-top content-top-green"><i class="fa-solid fa-blog di"></i> Latest Blogs</h2>
                <div class="content-area-bottom">
                    <p>Read all this garbage.</p>
                    <div class="projects">
                        {% if blogs %}
                            {% for i in blogs[0:4] %}
                                <div class="content-box">
                                    <div class="content-box-top content-top-purple">
                                        <h3 class="content-title">{{ i.title }}</h3>
                                    </div>

                                    <div class="content-box-bottom">
                                        <p class="content-timestamp">{{ i.timestamp.strftime(strf) }}</p>
                                        <div class="box content-desc">
                                            {{ i.summary }}
                                        </div>

                                        <a href="{{ url_for('in_blog.in_blog', blog=i.uid) }}" rel="nopener noreferrer" target="_blank"><button class="button">Read More</button></a>
                                    </div>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

templates/in_blog.html
{% extends "base.html" %}
{% block title %}{{ blog.title }}{% endblock %}

{% block main %}
    <div class="blog-area">
        <a href="/blog/" class="blog-exit-link" rel="noopener noreferrer">Go back</a>
        <p class="blog-title">{{ blog.title }}</p>

        <div class="blog-area-content">
            {% autoescape off %}
                {{ blog.content }}
            {% endautoescape %}
        </div>
    </div>
{% endblock %}

templates/projects.html
{% extends "base.html" %}
{% block title %}Projects{% endblock %}

{% block main %}
<div class="section home-welcum-section">
    <span class="welcome-title">
        <span class="letter">P</span>
        <span class="letter">r</span>
        <span class="letter">o</span>
        <span class="letter">j</span>
        <span class="letter">e</span>
        <span class="letter">c</span>
        <span class="letter">t</span>
        <span class="letter">s</span>
    </span>

    <p class="welcome-subtitle">This is what you are here for, if at all.</p>
</div>

<div class="page-content">
    <section class="section">
        <div class="content-area content-area-yellow">
            <h2 class="content-area-top content-top-yellow"><i class="fa-solid fa-globe di"></i> Completed</h2>
            <div class="content-area-bottom">
                <p>Completed and ready2go. They may recieve updates but the full version is completed from start to finish.</p>

                <div class="projects">
                    {% if projects %}
                        {% for project in projects %}
                            {% if project.project_category == "completed" %}
                                {% include("includes/project_box.html") %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
        </div>
    </section>
    <section class="section">
        <div class="content-area content-area-yellow">
            <h2 class="content-area-top content-top-yellow"><i class="fa-solid fa-globe di"></i> Under Construction</h2>
            <div class="content-area-bottom">
                <p>Projects that are being worked on, but aren't released to the public.</p>

                <div class="projects">
                    {% if projects %}
                        {% for project in projects %}
                            {% if project.project_category == "construction" %}
                                {% include("includes/project_box.html") %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
        </div>
    </section>

    <section class="section">
        <div class="content-area content-area-yellow">
            <h2 class="content-area-top content-top-yellow"><i class="fa-solid fa-globe di"></i> Scrapped</h2>
            <div class="content-area-bottom">
                <p>Were being worked once upon a time, but no longer.</p>

                <div class="projects">
                    {% if projects %}
                        {% for project in projects %}
                            {% if project.project_category == "scrapped" %}
                                {% include("includes/project_box.html") %}
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
        </div>
    </section>
</div>
{% endblock %}

templates/signin.html
{% extends "base.html" %}
{% block main %} 

<div class="section home-welcum-section">
    <h2 class="welcome-title">Sign In</h2>
</div>

<form action="{{ url_for('signin.signin') }}" method="POST">
    <input type="password" name="token" id="token" placeholder="Token" class="wide" required />
    <input type="submit" class="wide" value="Log in">
</input>

{% endblock %}